language: node_js
node_js:
  - '10'
deploy:
  provider: gae
  keyfile: gae-key.json
  project: fanger-app
before_install:
  - openssl aes-256-cbc -K $encrypted_a75fb37527d8_key -iv $encrypted_a75fb37527d8_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
