language: node_js
node_js:
  - '10'
deploy:
  provider: gae
  keyfile: gae-key.json
  project: fanger-app
before_install:
  - openssl aes-256-cbc -K $encrypted_522ff3e08e03_key -iv $encrypted_522ff3e08e03_iv  -in gae-key.json.enc -out gae-key.json -d
