runtime: nodejs10
env: standard
instance_class: F1
handlers:
  - url: ".*"
    script: auto
    secure: always
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  min_instances: 0
  max_instances: 2